[package]
name = "supra_utils"
version = "0.0.1"
published-at = "0x7237ec8436ef7e927c45470db6db3a834dd84cf903aedee3844e847fe4805399"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sui = "0x2"
supra_utils = "0x7237ec8436ef7e927c45470db6db3a834dd84cf903aedee3844e847fe4805399"
